# Generated by Django 3.2.23 on 2024-02-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Facinorous Fluffballs', 'Fluffy'), ('Reptillian Villains', 'Scaly'), ('Feathered Fiends', 'Feathers')], max_length=40, null=True),
        ),
    ]
