# Generated by Django 3.2.23 on 2024-02-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Facinorous Fluffballs', 'Fluffy'), ('Reptillian Villains', 'Scaly'), ('Feathered Fiends', 'Feathers')], default='Facinorous Fluffballs', max_length=40),
        ),
    ]
