# Generated by Django 3.2.23 on 2024-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fluffy', 'Facinorous Fluffballs'), ('scaly', 'Reptillian Villains'), ('feathers', 'Feathered Fiends')], default='fluffy', max_length=40),
        ),
    ]
