# Generated by Django 3.2.23 on 2024-03-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240216_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Facinorous Fluffballs', 'Facinorous Fluffballs'), ('Reptillian Villains', 'Reptillian Villains'), ('Feathered Fiends', 'Feathered Fiends')], default='fluffy', max_length=40),
        ),
    ]
