# Generated by Django 3.2.23 on 2024-03-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Facinorous Fluffballs', 'Facinorous Fluffballs'), ('Reptillian Villains', 'Reptillian Villains'), ('Feathered Fiends', 'Feathered Fiends')], default=('Facinorous Fluffballs', 'Facinorous Fluffballs'), max_length=40),
        ),
    ]
