# Generated by Django 3.2.23 on 2024-02-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_alter_reaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('CROWN', 'CROWN'), ('GOOD', 'GOOD'), ('LOVE', 'LOVE')], max_length=50),
        ),
    ]
